export enum ACTION_CONSTANTS {
    COINS_LIST_REQUEST = 'COINS_LIST_REQUEST',
    COINS_LIST_SUCCESS = 'COINS_LIST_SUCCESS',
    COINS_LIST_FAIL = 'COINS_LIST_FAIL',
    COIN_SINGLE_REQUEST = 'COIN_SINGLE_REQUEST',
    COIN_SINGLE_SUCCESS = 'COIN_SINGLE_SUCCESS',
    COIN_SINGLE_FAIL = 'COIN_SINGLE_FAIL'
}